
#include <stdexcept>

void throw_exception() {
	throw std::runtime_error("test_msg");
}
